version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    platform: linux/arm64/v8
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html

  db:
    image: mysql:8.0
    platform: linux/arm64/v8
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: somewordpress
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: arm64v8/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: somewordpress

  sftp:
    image: emberstack/sftp
    platform: linux/arm64/v8
    restart: always
    ports:
      - "2222:22"
    volumes:
      - wordpress_data:/home/sftp/wordpress
    environment:
      SFTP_USERS: wordpress:password:1001:1001:wordpress

volumes:
  wordpress_data:
  db_data: 